jason:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: jason_csiet
    username: root
    password: "123456"
  redis:
    host: localhost
    password: "123456"
    port: 6379
    database: 11